name: Official Release

on:
  # [ Note: Manually Trigger the Workflow ]
  # 1. Go to Actions under pytorch/data repo
  # 2. In the left sidebar, click the workflow you want to run
  # 3. Above the list of workflow runs, select Run workflow
  # 4. Use the Branch dropdown to select the release/* branch
  # 5. Click Run workflow
  workflow_dispatch:

jobs:
  build_and_upload_wheel:
    if: github.repository == 'sehoffmann/atmodata' && github.ref_type == 'tag'
    uses: ./.github/workflows/build_and_upload_wheel.yml
    with:
      branch: ""
      real-pypi: true
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
