name: Run Tests
on:
  push:
    branches:
      - develop
    tags:  # ignores tag pushes
    paths:
      - 'atmodata/**'
      - 'test/**'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        python-version:
          #- "3.8"
          #- "3.9"
          - "3.10"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          pip3 install --pre torchdata --extra-index-url https://download.pytorch.org/whl/nightly/cpu
          pip3 install --pre torch --extra-index-url https://download.pytorch.org/whl/nightly/cpu
          pip3 install -r requirements.txt
          echo "/home/runner/.local/bin" >> $GITHUB_PATH
      
      - name: Install atmodata
        run: |
          pip3 install .
      
      - name: Install test requirements
        run: pip3 install -r test/requirements.txt
      
      - name: Run Tests
        run:
          pytest --no-header -v test
